#!/bin/sh
# This script prompts the user with the message which is $1
# After chosing either 'yes' or 'no' $2 will be executed
options="Nein\\nJa"
chosen=$(printf "$options" | dmenu -i -p "$1")

if [ "$chosen" = "Ja" ]; then
  $2
fi
#[ "$(printf "No\\nYes" | dmenu -i -p "$1" -nb darkred -sb red -sf white -nf gray )" = "Yes" ] && $2
